steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-south1-docker.pkg.dev/cloudcgcpdockerdemo/docker-repo/app-image',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'asia-south1-docker.pkg.dev/cloudcgcpdockerdemo/docker-repo/app-image'
    ]

images:
  - 'asia-south1-docker.pkg.dev/cloudcgcpdockerdemo/docker-repo/app-image'

options:
  logging: CLOUD_LOGGING_ONLY
